### ISSUE TITLE
Can we have some data for running it ?

### ISSUE THREAD

**Issue by dineshb302** [logpai/Log3C#4]

**Comment by ShilinHe** [comment]
Sorry the data is highly confidential at Microsoft and cannot be released.

**Comment by dineshb302** [comment]
Thanks for replying. I can understand the issue, it would be great help in understanding if you could provide the code for matrix generation from parsed logs

**Comment by ShilinHe** [comment]
Thanks for your understanding! The matrix is actually very easy to generate, and I will share with the procedures:
1. parse the logs into log events, and link logs as log sequences by task/job ID.
2. for each log sequence, an event count vector can be generated to represent it. To do so, count the number of each log event type in a log sequence. If a log event never occurs, the count of it is zero.
3. compose all the event count vectors to be the matrix of shape (N, D), where N is the number of log sequences (depends on the number of tasks/jobs), D is the total number of log events in the log file.

Should you have any questions, feel free to ask me.

**Comment by shoaib-intro** [comment]
Hi, I went through paper and and repo many time but could not understand completely how you are making sequences:
- I am done with creating logke sequences with process_id/pod_id after parsing from logparse(logpai-Spell)
- once we are done with count vectors of each log keys (this will not disturb the sequence? as logkey 21 occurs 120 times before than logkey 14 but in counting may replaced)
- I totally did not understand how to generate matrix could you please share code for this!
would be great help I meshed since long on this topic!

**Comment by shoaib-intro** [comment]
Hi, I went through paper and and repo many time but could not understand completely how you are making sequences:
- I am done with creating logke sequences with process_id/pod_id after parsing from logparse(logpai-Spell)
- once we are done with count vectors of each log keys (this will not disturb the sequence? as logkey 21 occurs 120 times before than logkey 14 but in counting may replaced)
- I totally did not understand how to generate matrix could you please share code for this!
would be great help I meshed since long on this topic! @ShilinHe could you please help paper is going out of my understanding how to create matrix...
